- name: pg
  type: pg
  allow: "*"
  connection:
    host: ${DB_HOST:-localhost}
    port: ${DB_PORT:-5432}
    database: ${DB_NAME:-jira_clone}
    user: ${DB_USER:-jira_user}
    password: ${DB_PASS}
    ssl:
      rejectUnauthorized: false
